### ISSUE TITLE
"AlgorithmsRadixSort" can't sort long properly, and also fails under CPU

### ISSUE THREAD

**Issue by GeoBIM2020** [m4rs-mt/ILGPU.Algorithms#20]
It will give something like following result (negative is listed behind positive) if there are negative long in the array.
1,2,3,4,5,-5,-4,-3,-2,-1

It also throws error message if accelarator is CPU

**Comment by m4rs-mt** [comment]
The radix-sort algorithm that is currently implemented assumes unsigned values. We could add support for negative values in the future by taking the sign bit into account.
