### ISSUE TITLE
Add missing test cases for Scan, Reduce, Transform etc.

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU.Algorithms#22]
The current test projects do not cover the high-level functions `Scan`, `Reduce`, `Transform` etc. We should include additional test cases to cover these functions.

**Comment by albosc** [comment]
I will take a look at these functions and write test cases to cover them.

**Comment by MoFtZ** [comment]
@albosc I've [raised a PR](https://github.com/m4rs-mt/ILGPU.Algorithms/pull/26) to fix some issues with RadixSort. Hopefully this helps with your unit tests.
