### ISSUE TITLE
TanF, TanhF

### ISSUE THREAD

**Issue by Mattias-NCVIB** [m4rs-mt/ILGPU.Algorithms#33]
Hi, I'm trying to add Tan, Tanh, Log and Exp to my code, but I get the error:

"The function 'TanF' does not have an intrinsic implementation for this backend. 'EnableAlgorithms' from the Algorithms library not invoked?"

Enable Elgorithms has been invoked. Sin/Cos worked

I tried looking at the code for ILGPU.Algorithms, but getting it to compile is a challenge. But from the CUDA documentation, it seems to be natively supported;

// https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html
__device__ ​ float tanf ( float  x )
    Calculate the tangent of the input argument. 

cheers,
/m

**Comment by Mattias-NCVIB** [comment]
Oh,

**Comment by mfagerlund** [comment]
Turns out you have to run EnableAlgorithms BEFORE you create the accelerator.
