### ISSUE TITLE
Feature request: Histograms and distinct lists

### ISSUE THREAD

**Issue by martenf** [m4rs-mt/ILGPU.Algorithms#5]
Histograms are quite commonly used for image analysis.
Creating distinct lists aka a sorted or unsorted list where every element is unique from an arbitrary list can also be used for everything from lossless image encoding to data analysis.

**Comment by m4rs-mt** [comment]
@MartenF Thank you very much for your feedback. It definitely makes sense to add this.

**Comment by MoFtZ** [comment]
**Histogram API Proposal**

1. The algorithm will support N-dimensional input data.
    - The user may want to supply input as 2D arrays.

1. The algorithm will iterate over input data, and for each element, determine a bin/bucket location.
    - What information does this calculation require?
        - [ ] Number of bins?
        - [ ] Input dimensions?
        - [ ] Current input index?
    - [ ] Is there a preferred terminology for bin versus bucket? or some other suggestion?
    - [ ] Are there common rules for determining histogram bin location that we should implement by default?
        - e.g. `binLocation = value % numBins;`
    - [ ] Do we require more than a simple +1 increment for each bin?

1. The algorithm will support custom data types for bins.
    - The user may want bins to be a `UInt8` or `UInt16` to reduce memory usage.
    - The user may want bins to be signed (e.g. `Int32`) for convenience.
    - The user may want bins to have a large range (e.g. `UInt64`).
    - The user may want bins to be a custom struct of their own design.

1. The algorithm will support a variable number of bins:
    - Minimum 2 bins, and up to `Int.MaxValue` (or available memory)
    - [ ] Are variable-sized histograms required, or nice-to-have?

1. The caller of the algorithm is responsible for initializing the histogram output buffer to zero.
    - This allows the output buffer to be re-used in order to accumulate results.

**Kernel**
```csharp
public delegate void Histogram<TInputType, TIndex, TBinType>(
    AcceleratorStream stream,
    ArrayView<TInputType, TIndex> view,
    ArrayView<TBinType> value)
    where TInputType : unmanaged
    where TBinType : unmanaged
    where TIndex : unmanaged, IIndex, IGenericIndex<TIndex>;
```
**Create Kernel**
```csharp
public interface IHistogramOperation<TInputType>
    where TInputType : unmanaged
{
    int ComputeHistogramBin(TInputType value, int numBins);
}

// NB: Might need some overloads to make calling the common 1D and 2D cases easier
Histogram<TInputType, TIndex, TBinType> CreateHistogram<TInputType, TIndex, TBinType, THistogramOperation>(
    this Accelerator accelerator,
    int numBins)
    where TInputType : unmanaged
    where TBinType : unmanaged
    where TIndex : unmanaged, IIndex, IGenericIndex<TIndex>
    where THistogramOperation : struct, IHistogramOperation<TInputType>
```
**Usage**
```csharp
 public readonly struct MyHistogramOperation : IHistogramOperation<long>
{
    int ComputeHistogramBin(long value, int numBins)
    {
        return value % numBins;
    }
}

var histogramKernel = accelerator.CreateHistogram<long, Index1, uint, MyHistogramOperation>(numBins: 256);
using var inputBuffer = accelerator.Allocate<long>(1024);
using var outputBuffer = accelerator.Allocate<uint>(256);

inputBuffer.CopyFrom(/* some user-supplied input */);
outputBuffer.MemSetToZero();
histogramKernel(accelerator.DefaultStream, inputBuffer, outputBuffer);
```
