### ISSUE TITLE
Question: Is it necessary to call context.EnableAlgorithms() to use the algorithm library in the kernel function?

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU.Algorithms#51]

**Comment by MoFtZ** [comment]
hi @xxl-cc, yes, you should to call `EnableAlgorithms`.

In theory, some of the functionally in the Algorithms library may work without calling EnableAlgorithms. However, that is an implementation detail - it may change at any time e.g. when a bug is fixed, or when the internals are refactored.

**Comment by m4rs-mt** [comment]
I think this issue has been resolved. If the issue still persists, please open a new issue in the ILGPU project.
