### ISSUE TITLE
ILGPU 0.8 compatibility issue

### ISSUE THREAD

**Issue by NicolasG3** [m4rs-mt/ILGPU.Algorithms#6]
Hi,
I experienced an error with the very last ILGPU 0.8 related to ILGPU.Algorithms.
ILGPU.Algorithms compatibility is broken by a missing method `PTXCodeGenerator.AllocatePrimitive()`

**Comment by m4rs-mt** [comment]
@NicolasG3 Yes, you are right. It should be `AllocateHardware`. Going to fix this.
